/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.aquarelah.isbnPdfExtractor;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.SQLException;
import java.util.concurrent.ExecutionException;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.DefaultParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;


public class App {

	public static void main(String[] args) throws IOException, InterruptedException, ExecutionException, SQLException, ParseException {
		
		CommandLineParser cmdLineParser = new DefaultParser();
		PrintWriter writer = new PrintWriter(System.out);
		HelpFormatter formatter = new HelpFormatter();
		Options options = new Options();
		
		options.addOption(Option.builder()
				.longOpt("directory")
				.argName("directory")
				.hasArg()
				.desc("directory path to pdf files")
				.build());

		CommandLine cmd = cmdLineParser.parse(options, args);
		 
		if (!cmd.hasOption("directory")) {
			formatter.printUsage(writer, 80, "java -jar build/libs/isbnPdfExtractor-all.jar", options);
			writer.flush();
			System.exit(0);
		} 
		
		Client cl = new Client(cmd.getOptionValue("directory"));
		cl.execute();
		
	}
	
}
